// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-OkKMgZx4uP-SdjAxOaeSDvDRfuG6GtU',
    appId: '1:1048839283637:web:d4794875c5b5870fefeffc',
    messagingSenderId: '1048839283637',
    projectId: 'grenco-cdde5',
    authDomain: 'grenco-cdde5.firebaseapp.com',
    storageBucket: 'grenco-cdde5.firebasestorage.app',
    measurementId: 'G-Z2349P813K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQqCE2dZR4iZNDcSzjsoIY2Mq3Lhx6uM',
    appId: '1:1048839283637:android:78f91b1a147586ceefeffc',
    messagingSenderId: '1048839283637',
    projectId: 'grenco-cdde5',
    storageBucket: 'grenco-cdde5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADwuffFTVS844UYCRPGg3lWwLQKBz3mcA',
    appId: '1:1048839283637:ios:55d08428fbabb4baefeffc',
    messagingSenderId: '1048839283637',
    projectId: 'grenco-cdde5',
    storageBucket: 'grenco-cdde5.firebasestorage.app',
    iosBundleId: 'com.example.grenco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADwuffFTVS844UYCRPGg3lWwLQKBz3mcA',
    appId: '1:1048839283637:ios:55d08428fbabb4baefeffc',
    messagingSenderId: '1048839283637',
    projectId: 'grenco-cdde5',
    storageBucket: 'grenco-cdde5.firebasestorage.app',
    iosBundleId: 'com.example.grenco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-OkKMgZx4uP-SdjAxOaeSDvDRfuG6GtU',
    appId: '1:1048839283637:web:1fde747f45c8e722efeffc',
    messagingSenderId: '1048839283637',
    projectId: 'grenco-cdde5',
    authDomain: 'grenco-cdde5.firebaseapp.com',
    storageBucket: 'grenco-cdde5.firebasestorage.app',
    measurementId: 'G-C3P46T558Y',
  );
}
